# Generated by Django 4.0.5 on 2022-08-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_snacks_alter_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snacks',
            old_name='name',
            new_name='snack_name',
        ),
    ]
