# Generated by Django 4.0.5 on 2022-08-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_snacks_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snacks',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
    ]
