# Generated by Django 4.0.5 on 2022-08-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
