# Generated by Django 4.0.5 on 2022-08-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ip_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='snacks',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='page_views', to='webapp.ip_model'),
        ),
    ]
