# Generated by Django 4.0.5 on 2022-08-16 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_ip_model_snacks_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snacks',
            name='views',
        ),
        migrations.DeleteModel(
            name='ip_model',
        ),
    ]
